### ISSUE TITLE
Reauthentication fails with MariaDB

### ISSUE THREAD

**Issue by bgrainger** [bgrainger/MySqlConnector#28]
As reported here: http://stackoverflow.com/questions/38362581/getting-access-denied-for-user-every-2nd-hit

**Comment by alperencaliskan** [comment]
Thank you for this library.

When using connection for 2nd time, provider gets connection from connection pool then eventually hits this line (MySqlConnection.cs:137)
`else if (m_connectionStringBuilder.ConnectionReset)
				{.....`

But although there is no ConnectionReset param in connection string, default value for this param is **true** because of this code block;
`AddOption(ConnectionReset = new MySqlConnectionStringOption<bool>(
				keys: new[] { "Connection Reset", "ConnectionReset" },
				defaultValue: true));`

then runs the code with this comment
```
// MySQL doesn't appear to accept a replayed hashed password (using the challenge from the initial handshake), so just send zeroes
// and expect to get a new challenge
............
```

Workaround is adding "ConnectionReset = false" to connection string.

**Comment by bgrainger** [comment]
What version of MySQL Server are you using?

**Comment by alperencaliskan** [comment]
> Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 95
Server version: 10.1.13-MariaDB mariadb.org binary distribution

> Copyright (c) 2000, 2016, Oracle, MariaDB Corporation Ab and others.

Comes with xampp / windows.

**Comment by bgrainger** [comment]
Fixed in Fixed in https://www.nuget.org/packages/MySqlConnector/0.1.0-alpha09

**Comment by alperencaliskan** [comment]
Thanks
