### ISSUE TITLE
Only 'mysql_native_password' authentication method is supported.

### ISSUE THREAD

**Issue by ggsandro** [bgrainger/MySqlConnector#96]
Hi, Bradley.

I have installed your MySQL connector for Core and I have got such error (screenshot):

http://screencast.com/t/Lagn0jL8unf

I have no clue what is wrong, maybe you can tell me what is the problem? Connection string is ok, I have check it. Sorry for such noobie question, but I'm new to MySQL.

**Comment by bgrainger** [comment]
The issue here is that MySQL supports different ways of authenticating to the server (see [list here](https://dev.mysql.com/doc/refman/5.7/en/authentication-plugins.html)). This connector currently only supports `mysql_native_password`. Unfortunately the exception message doesn't state the name of the unsupported plugin (which is something I should fix).

What version of MySQL Server are you using? Do you know if there are any custom authentication plugins installed?

It's possible you're using an older version of MySQL Server with `mysql_old_password`. If so, that authentication method has been deprecated, and you may wish to [migrate away from it](https://dev.mysql.com/doc/refman/5.7/en/account-upgrades.html) as a workaround in the meantime.

**Comment by bgrainger** [comment]
Can you please update to [0.2.1](https://www.nuget.org/packages/MySqlConnector/0.2.1) and paste the new exception message here?

**Comment by ggsandro** [comment]
I update MySQL from 5.1 (Installed by Wordpress installer) to 5.7 and everything works now. It was a problem of custom Wordpress settings I think. Thanks, Bradley.
